import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import * as React from "react";
import { Providers } from "./providers";
import { ReduxProviders } from "./redux/provider"

import ThemeSwitcher from './components/shared/themeSwitcher'
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className='dark'>
        <body className={inter.className}>
          {/* {children} */}
          <ReduxProviders>
          <Providers>

          <header className='py-6'>
            <nav className='container flex items-center justify-between'>
              <ul>
                <li>
                  <Link href='/'>Home</Link>
                </li>
              </ul>
              <ThemeSwitcher />
            </nav>
          </header>
            {children}</Providers>
            </ReduxProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
